services:
  drawdb:
    image: node:20-alpine
    container_name: drawdb
    ports:
      - 3000:5173
    working_dir: /app
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: sh -c "npm install && npm run dev -- --host"
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env

  drawdb-server:
    image: node:20-alpine
    container_name: drawdb-server
    ports:
      - ${PORT:-5000}:${PORT:-5000}
    working_dir: /app
    volumes:
      - ./backend:/app 
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    networks:
      - default
    env_file:
      - .env

networks:
  default:
    driver: bridge